---
# Install Amazon EFS mount helper
- name: Install amazon-efs-utils
  apt:
    name:
    - git
    - make
    - binutils
    state: present
    update_cache: yes
  become: true

- name: Clone the amazon-efs-utils tool from GitHub
  git:
    repo: https://github.com/aws/efs-utils
    dest: "{{ install_folder }}/efs-utils"
  become: true

- name: Build the amazon-efs-utils DEB package if it was not already builded
  shell: ./build-deb.sh
  args:
    chdir: "{{ install_folder }}/efs-utils/"
    creates: "{{ install_folder }}/efs-utils/build/amazon-efs-utils*deb"
  become: yes

- name: Finding builded amazon-efs-utils DEB package
  find:
    paths: "{{ install_folder }}/efs-utils/build"
    patterns: "amazon-efs-utils*deb"
  register: deb_file

- name: Install the amazon-efs-utils DEB package
  apt:
    deb: "{{ item.path }}"
    state: present
  become: true
  with_items: "{{ deb_file.files }}"
