---
# Mount Amazon EFS
- name: Register variable for Amazon EFS
  set_fact:
    efs_fs_id: "{{ lookup('env','efs_fs_id') }}"
    efs_mount_point: "{{ lookup('env','efs_mount_point') }}"

- name: Install Amazon EFS mount helper on RHEL based OS
  include: install_rpm.yml
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

- name: Install Amazon EFS mount helper on DEB based OS
  include: install_deb.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Create directory for Amazon EFS mount point
  file:
    path: "{{ efs_mount_point }}"
    state: directory
    owner: root
    group: root
    mode: 0644
  become: true

- name: Mount Amazon EFS
  mount:
    path: "{{ efs_mount_point }}"
    src: "{{ efs_fs_id }}"
    fstype: efs
    opts: defaults,_netdev
    state: mounted
  become: true
